
# coding: utf-8

# In[4]:


import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import os
system = 57779
newpath = "./" + str(system) + "figs"
if not os.path.exists(newpath):
    os.makedirs(newpath)
resultsFileName = 'resultscurrent.csv'
results = np.genfromtxt(resultsFileName)
results = results[-32:,:]
print(results.shape)
plt.plot(results[:,0],label='NormB')
plt.plot(results[:,1],label='NormAlt')
plt.plot(results[:,2],label='RookB')
plt.plot(results[:,3],label='RookAlt')
plt.plot(results[:,4],label='Rook')
plt.plot(results[:,5],label='Norm')
plt.legend()
plt.title("Means")
plt.show()
plt.clf()
plt.plot(results[:,6],label='NormB & NormAlt')
plt.plot(results[:,7],label='RookB & RookAlt')
plt.plot(results[:,8],label='Rook & Norm')
plt.legend()
plt.title("Avg Means")
plt.show()
plt.clf()
aNvN = (np.mean(np.array(results[0])) + np.mean(np.array(results[1]))) / 2.0
aRvR = (np.mean(np.array(results[2])) + np.mean(np.array(results[3]))) / 2.0
aRvN = (np.mean(np.array(results[4])) + np.mean(np.array(results[5]))) / 2.0
plt.plot(np.divide(results[:,1] - results[:,0],aNvN),label='NormB & NormAlt')
plt.plot(np.divide(results[:,3] - results[:,2],aRvR),label='RookB & RookAlt')
plt.plot(np.divide(results[:,4] - results[:,5],aRvN),label='Rook & Norm')
plt.legend()
plt.title("Avg Means")
plt.show()
plt.clf()
plt.plot(np.divide(results[:,1] - results[:,0],results[:,6]),label='$c_{K_i}$')
plt.plot(np.divide(results[:,3] - results[:,2],results[:,7]),label='$c_{U_i}$')
plt.plot(np.divide(results[:,4] - results[:,5],results[:,8]),label='$c_{H_i}$')
plt.legend()
plt.title("Avg Means")
plt.ylim(-0.05,0.2)
plt.legend()
plt.title("Scaled Mean Comparisons (unaltered case)")
plt.ylabel('Mean Difference Scaled by Mean Avg')
plt.xlabel('Iteration')
plt.savefig(str(system) + 'figs/method2Alt.png')
plt.show()
plt.clf()
plt.plot(np.divide(results[:,0],results[:,6]),label='NormB')
plt.plot(np.divide(results[:,1],results[:,6]),label='NormAlt')
plt.plot(np.divide(results[:,2],results[:,7]),label='RookB')
plt.plot(np.divide(results[:,3],results[:,7]),label='RookAlt')
plt.plot(np.divide(results[:,4],results[:,8]),label='Rook')
plt.plot(np.divide(results[:,5],results[:,8]),label='Norm')
plt.legend()
plt.title("Scaled Means")
plt.show()
plt.clf()
plt.plot(results[:,9],label='NormB')
plt.plot(results[:,10],label='NormAlt')
plt.plot(results[:,11],label='RookB')
plt.plot(results[:,12],label='RookAlt')
plt.plot(results[:,13],label='Rook')
plt.plot(results[:,14],label='Norm')
plt.legend()
plt.title("Std Devs")
plt.show()
plt.clf()
plt.plot(results[:,15],label='NormB')
plt.plot(results[:,16],label='NormAlt')
plt.plot(results[:,17],label='RookB')
plt.plot(results[:,18],label='RookAlt')
plt.plot(results[:,19],label='Rook')
plt.plot(results[:,20],label='Norm')
plt.legend()
plt.title("RMSs")
plt.show()
plt.clf()
plt.plot(results[:,21],label='NormB & NormAlt')
plt.plot(results[:,22],label='RookB & RookAlt')
plt.plot(results[:,23],label='Rook & Norm')
plt.legend()
plt.title("Avg RMSs")
plt.show()
plt.clf()
plt.plot(np.divide(results[:,15],results[:,21]),label='NormB')
plt.plot(np.divide(results[:,16],results[:,21]),label='NormAlt')
plt.plot(np.divide(results[:,17],results[:,22]),label='RookB')
plt.plot(np.divide(results[:,18],results[:,22]),label='RookAlt')
plt.plot(np.divide(results[:,19],results[:,23]),label='Rook')
plt.plot(np.divide(results[:,20],results[:,23]),label='Norm')
plt.legend()
plt.title("Scaled RMSs")
plt.show()
plt.clf()
plt.plot(results[:,26],label='$c_{H_i}$')
plt.plot(results[:,24],label='$c_{K_i}$')
plt.plot(results[:,25],label='$c_{U_i}$')
plt.legend()
plt.title("Scaled Mean Comparisons (altered case)")
plt.ylabel("Mean difference scaled by mean avg")
plt.xlabel("Iteration")
plt.ylim(-0.05,0.2)
plt.savefig(str(system) + "figs/diff3Comp.png")
plt.show()
plt.clf()
plt.plot(results[:,27],label='NormB v NormAlt')
plt.plot(results[:,28],label='RookB v RookAlt')
plt.plot(results[:,29],label='Rook v Norm')
plt.legend()
plt.title("Scaled RMS Comparisons")
plt.show()
plt.clf()
plt.plot(results[:,30],label='NormB v NormAlt')
plt.plot(results[:,31],label='RookB v RookAlt')
plt.plot(results[:,32],label='Rook v Norm')
plt.legend()
plt.title("RMS of Comparisons")
plt.show()
plt.clf()
plt.plot(results[:,33],label='NormB v NormAlt')
plt.plot(results[:,34],label='RookB v RookAlt')
plt.plot(results[:,35],label='Rook v Norm')
plt.legend()
plt.title("Binary Comparisons")
plt.show()
plt.clf()
plt.plot(results[:,36],label='NormB & NormAlt')
plt.plot(results[:,37],label='RookB & RookAlt')
plt.plot(results[:,38],label='Rook & Norm')
plt.legend()
plt.title("RMS of Loss of model history Comparisons")
plt.show()
plt.clf()

plt.plot(np.divide(results[:, 39] - results[:, 41], results[:, 46]), label='$c_{k_i}$ $/$ $a_{k_i}$')
plt.plot(np.divide(results[:, 40] - results[:, 41], results[:, 45]), label='$c_{u_i}$ $/$ $a_{u_i}$')
plt.ylim(-0.05,0.2)
plt.legend()
plt.title("Scaled Mean Comparisons (unaltered case)")
plt.ylabel('Mean Difference Scaled by Mean Avg')
plt.xlabel('Iteration')
plt.savefig(str(system) + 'figs/method1Unalt.png')
plt.show()
plt.clf()

system = 57779
newpath = "./" + str(system) + "figs"
if not os.path.exists(newpath):
    os.makedirs(newpath)
resultsFileName = 'results/' + str(system) + 'system/resultsa13.csv'
results = np.genfromtxt(resultsFileName)
results = results[-32:,:]
print(results.shape)

plt.plot(np.divide(results[:,1] - results[:,0],results[:,6]),label='$c_{K_i}$')
plt.plot(np.divide(results[:,3] - results[:,2],results[:,7]),label='$c_{U_i}$')
plt.plot(np.divide(results[:,4] - results[:,5],results[:,8]),label='$c_{H_i}$')
plt.legend()
plt.title("Avg Means")
plt.ylim(-0.05,0.2)
plt.legend()
plt.title("Scaled Mean Comparisons (altered case)")
plt.ylabel('Mean Difference Scaled by Mean Avg')
plt.xlabel('Iteration')
plt.savefig(str(system) + 'figs/method2Alt.png')
plt.show()
plt.clf()

plt.plot(np.divide(results[:, 39] - results[:, 41], results[:, 46]), label='$c_{k_i}$ $/$ $a_{k_i}$')
plt.plot(np.divide(results[:, 40] - results[:, 41], results[:, 45]), label='$c_{u_i}$ $/$ $a_{u_i}$')
plt.ylim(-0.05,0.2)
plt.legend()
plt.title("Scaled Mean Comparisons (altered case)")
plt.ylabel('Mean Difference Scaled by Mean Avg')
plt.xlabel('Iteration')
plt.savefig(str(system) + 'figs/method1Alt.png')
plt.show()
plt.clf()

# plt.plot(results[:,39],label='Norm3 on NN')
# plt.plot(results[:,40],label='Rook3 on NN')
# plt.plot(results[:,41],label='Norm4 on NN')
# plt.plot(results[:,42],label='Norm3 on RR')
# plt.plot(results[:,43],label='Rook3 on RR')
# plt.plot(results[:,44],label='Norm4 on RR')
# plt.plot(results[:,69],label='Norm5 on NN')
# plt.legend()
# plt.title("Means")
# plt.show()
# plt.clf()
# plt.plot(results[:,45],label='Rook3 & Norm3 on NN')
# plt.plot(results[:,46],label='Norm4 & Norm3 on NN')
# plt.plot(results[:,47],label='Rook3 & Norm3 on RR')
# plt.plot(results[:,48],label='Norm4 & Norm3 on RR')
# plt.plot(results[:,70],label='Norm5 & Norm3 on NN')
# plt.legend()
# plt.title("Avg Means")
# plt.show()
# plt.clf()
# plt.plot(results[:,49],label='Norm3 on NN & RR')
# plt.plot(results[:,50],label='Rook3 on NN & RR')
# plt.legend()
# plt.title("Avg Means")
# plt.show()
# plt.clf()
# plt.plot(results[:,51],label='Norm3 on NN')
# plt.plot(results[:,52],label='Rook3 on NN')
# plt.plot(results[:,53],label='Norm4 on NN')
# plt.plot(results[:,54],label='Norm3 on RR')
# plt.plot(results[:,55],label='Rook3 on RR')
# plt.plot(results[:,56],label='Norm4 on RR')
# plt.plot(results[:,71],label='Norm5 on NN')
# plt.legend()
# plt.title("Std Devs")
# plt.show()
# plt.clf()
# plt.plot(results[:,57],label='Norm3 on NN')
# plt.plot(results[:,58],label='Rook3 on NN')
# plt.plot(results[:,59],label='Norm4 on NN')
# plt.plot(results[:,60],label='Norm3 on RR')
# plt.plot(results[:,61],label='Rook3 on RR')
# plt.plot(results[:,62],label='Norm4 on RR')
# plt.plot(results[:,72],label='Norm5 on NN')
# plt.legend()
# plt.title("RMS's")
# plt.show()
# plt.clf()
# plt.plot(results[:,63],label='Rook3 vs Norm3 on NN')
# plt.plot(results[:,64],label='Norm4 vs Norm3 on NN')
# plt.plot(results[:,65],label='Rook3 vs Norm3 on RR')
# plt.plot(results[:,66],label='Norm4 vs Norm3 on RR')
# plt.plot(results[:,73],label='Norm5 vs Norm3 on NN')
# plt.legend()
# plt.title("Scaled Mean Comparisons")
# plt.show()
# plt.clf()
# plt.plot(results[:,67],label='Norm3 on NN vs RR')
# plt.plot(results[:,68],label='Rook3 on NN vs RR')
# plt.legend()
# plt.title("Scaled Mean Comparisons")
# plt.show()
# plt.clf()
# plt.plot(results[:,64],label='$c_{k_i}$ $/$ $a_{k_i}$ from CNN trained on $X_{train}$')
# plt.plot(results[:,63],label='$c_{u_i}$ $/$ $a_{u_i}$ from CNN trained on $X_{train}$')
# plt.ylim(-0.05,0.2)
# plt.legend()
# plt.title("Scaled Mean Comparisons (altered case)")
# plt.ylabel('Mean Difference Scaled by Mean Avg')
# plt.xlabel('Iteration')
# plt.savefig(str(system) + 'figs/SMC-rvnNN-nvnNN-alt.png')
# plt.show()
# plt.clf()
# plt.plot(results[:,64],label='$c_{k_i}$ $/$ $a_{k_i}$ from CNN trained on $X_{train}$')
# plt.plot(results[:,73],label='$c_{u_i}$ $/$ $a_{u_i}$ from CNN trained on $X_{train}$')
# plt.ylim(-0.05,0.2)
# plt.legend()
# plt.title("Scaled Mean Comparisons (unaltered case)")
# plt.ylabel('Mean Difference Scaled by Mean Avg')
# plt.xlabel('Iteration')
# plt.savefig(str(system) + 'figs/SMC-rvnNN-nvnNN-unalt.png')
# plt.show()
# plt.clf()


# In[ ]:




